# Generated by Django 4.2 on 2023-04-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations_labren', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHorizontalMeans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.IntegerField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('annual', models.IntegerField(blank=True, null=True)),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sep', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_horizontal_means',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalHorizontalMeansSedesMunic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('annual', models.IntegerField(blank=True, null=True)),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sep', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_horizontal_means_sedes_munic',
                'managed': False,
            },
        ),
    ]
